version: '3'

services:
  db:
    image: mysql:8.1
    restart: unless-stopped
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty12345
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: qwerty12345

  laravel:
    image: pivotdude/laravel-template-backend:latest
    restart: unless-stopped
    command: bash -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  react:
    image: pivotdude/laravel-template-frontend:latest
    restart: unless-stopped
    command: pnpm run preview
    ports:
      - 5173:5173

volumes:
  dbdata: